/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

/**
 *
 * @author Farhan
 */
public class HomeLibrary extends javax.swing.JFrame {

    /**
     * Creates new form HomeLibrary
     */
    public HomeLibrary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stdbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        staticbtn = new javax.swing.JButton();
        issuebtn = new javax.swing.JButton();
        rtrnbtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdbtn.setBackground(new java.awt.Color(255, 255, 204));
        stdbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stdbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/member-add-on-300x300.png"))); // NOI18N
        stdbtn.setText("New Student");
        stdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdbtnActionPerformed(evt);
            }
        });
        getContentPane().add(stdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        bookbtn.setBackground(new java.awt.Color(255, 255, 204));
        bookbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/New book.png"))); // NOI18N
        bookbtn.setText("New Book");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 30, -1, -1));

        staticbtn.setBackground(new java.awt.Color(255, 255, 204));
        staticbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        staticbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/Statics.png"))); // NOI18N
        staticbtn.setText("Statics");
        staticbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticbtnActionPerformed(evt);
            }
        });
        getContentPane().add(staticbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 30, -1, -1));

        issuebtn.setBackground(new java.awt.Color(255, 255, 204));
        issuebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issuebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/issue.png"))); // NOI18N
        issuebtn.setText("Issue Book");
        issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebtnActionPerformed(evt);
            }
        });
        getContentPane().add(issuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 30, -1, -1));

        rtrnbtn.setBackground(new java.awt.Color(255, 255, 204));
        rtrnbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtrnbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/return-book-1-560407.png"))); // NOI18N
        rtrnbtn.setText("Return Book");
        rtrnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtrnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rtrnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 30, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/exit.png"))); // NOI18N
        jButton6.setText("LogOut");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/Library_Book_532388_1366x768.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rtrnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtrnbtnActionPerformed
        new Returnbook().setVisible(true);
    }//GEN-LAST:event_rtrnbtnActionPerformed

    private void staticbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staticbtnActionPerformed
        new statics().setVisible(true);
    }//GEN-LAST:event_staticbtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        new LoginLibrary().setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void stdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdbtnActionPerformed
     
             setVisible(true);
        new NewStudent().setVisible(true);
    
    }//GEN-LAST:event_stdbtnActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed

           setVisible(true);
        new NewBook().setVisible(true);
     
    }//GEN-LAST:event_bookbtnActionPerformed

    private void issuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebtnActionPerformed
      new IssueBook().setVisible(true);
    }//GEN-LAST:event_issuebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton issuebtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rtrnbtn;
    private javax.swing.JButton staticbtn;
    private javax.swing.JButton stdbtn;
    // End of variables declaration//GEN-END:variables
}
