/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nbookidtxt = new javax.swing.JTextField();
        nnametxt = new javax.swing.JTextField();
        npricetxt = new javax.swing.JTextField();
        npublishertxt = new javax.swing.JTextField();
        nyeartxt = new javax.swing.JTextField();
        savetxt = new javax.swing.JButton();
        closetxt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 51, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 184, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Publisher");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Publish Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        nbookidtxt.setBackground(new java.awt.Color(255, 255, 204));
        nbookidtxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nbookidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 200, -1));

        nnametxt.setBackground(new java.awt.Color(255, 255, 204));
        nnametxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 200, -1));

        npricetxt.setBackground(new java.awt.Color(255, 255, 204));
        npricetxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(npricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 200, -1));

        npublishertxt.setBackground(new java.awt.Color(255, 255, 204));
        npublishertxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(npublishertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, -1));

        nyeartxt.setBackground(new java.awt.Color(255, 255, 204));
        nyeartxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nyeartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 200, -1));

        savetxt.setBackground(new java.awt.Color(255, 255, 204));
        savetxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/save-icon--1.png"))); // NOI18N
        savetxt.setText("Save");
        savetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetxtActionPerformed(evt);
            }
        });
        getContentPane().add(savetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 391, -1, -1));

        closetxt.setBackground(new java.awt.Color(255, 255, 204));
        closetxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/red-x-mark-transparent-background-3.png"))); // NOI18N
        closetxt.setText("Close");
        closetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closetxtActionPerformed(evt);
            }
        });
        getContentPane().add(closetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 391, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Icons/123456.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetxtActionPerformed
       
          try
         {
             String bookid = nbookidtxt.getText();
             String nname = nnametxt.getText();
             String publisher = npublishertxt.getText();
             String price = npricetxt.getText();
             String publishery = nyeartxt.getText();
             
             java.sql.Connection con = sever.getCon();
             Statement st = con.createStatement();
           st.executeUpdate("insert into newbook values('"+bookid+"','"+nname+"','"+publisher+"','"+price+"','"+publishery+"')");
             JOptionPane.showMessageDialog(null,"Successfull updated");
             setVisible(false);
             new NewBook().setVisible(true);
         }catch(Exception e)
         {
               JOptionPane.showMessageDialog(null,"Book ID already exist");
                setVisible(false);
                    new NewBook().setVisible(true);
         }
    }//GEN-LAST:event_savetxtActionPerformed

    private void closetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closetxtActionPerformed
       setVisible(false);
    }//GEN-LAST:event_closetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nbookidtxt;
    private javax.swing.JTextField nnametxt;
    private javax.swing.JTextField npricetxt;
    private javax.swing.JTextField npublishertxt;
    private javax.swing.JTextField nyeartxt;
    private javax.swing.JButton savetxt;
    // End of variables declaration//GEN-END:variables
}
